force-app/main/default/objects/Account/fields/Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Identification_Number__c</fullName>
    <label>Identification Number</label>
    <type>Text</type>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Account/fields/Identification_Type__c.field-meta.xml
<CustomField>
    <fullName>Identification_Type__c</fullName>
    <label>Identification Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Drivers License</fullName>
            </value>
            <value>
                <fullName>National ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KYCVerificationRequest.cls
/**
 * @description KYC verification API request wrapper
 * @author Sai Chaganti
 */
public class KYCVerificationRequest {
    
    public String firstName;
    public String lastName;
    public String email;
    public String street;
    public String postalCode;
    public String country;
    public String city;
    public String identityType;
    public String identityNumber;
    
    public static KYCVerificationRequest buildFromAccount(Account account) {
        KYCVerificationRequest request = new KYCVerificationRequest();
        request.firstName = account.FirstName;
        request.lastName = account.LastName;
        request.email = account.PersonEmail;
        request.street = account.BillingStreet;
        request.postalCode = account.BillingPostalCode;
        request.country = account.BillingCountry;
        request.city = account.BillingCity;
        request.identityType = account.PersonContact.Identification_Type__c;
        request.identityNumber = account.PersonContact.Identification_Number__c;
        return request;
    }
    
    public String toJSON() {
        return JSON.serialize(this);
    }
    
    public Boolean isValid() {
        return String.isNotBlank(firstName) &&
               String.isNotBlank(lastName) &&
               String.isNotBlank(email) &&
               String.isNotBlank(identityType) &&
               String.isNotBlank(identityNumber);
    }
}